# Generated by Django 2.2.1 on 2020-01-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumifs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sumifs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoodsID', models.CharField(max_length=100)),
                ('GoodsIDSeqNo', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('GoodsPrice', models.IntegerField()),
            ],
        ),
    ]
